package com.xm.swc.dao;

import com.xm.swc.pojo.po.Portfoliopage;
import com.xm.swc.pojo.po.PortfoliopageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PortfoliopageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfoliopage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int countByExample(PortfoliopageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfoliopage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int deleteByExample(PortfoliopageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfoliopage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insert(Portfoliopage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfoliopage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insertSelective(Portfoliopage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfoliopage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    List<Portfoliopage> selectByExample(PortfoliopageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfoliopage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Portfoliopage record, @Param("example") PortfoliopageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfoliopage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExample(@Param("record") Portfoliopage record, @Param("example") PortfoliopageExample example);
}