package com.xm.swc.dao;

import com.xm.swc.pojo.po.Pricingpage;
import com.xm.swc.pojo.po.PricingpageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PricingpageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int countByExample(PricingpageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int deleteByExample(PricingpageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insert(Pricingpage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insertSelective(Pricingpage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    List<Pricingpage> selectByExample(PricingpageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Pricingpage record, @Param("example") PricingpageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExample(@Param("record") Pricingpage record, @Param("example") PricingpageExample example);
}