package com.xm.swc.dao;

import com.xm.swc.pojo.po.Servicepage;
import com.xm.swc.pojo.po.ServicepageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ServicepageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int countByExample(ServicepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int deleteByExample(ServicepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insert(Servicepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insertSelective(Servicepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    List<Servicepage> selectByExample(ServicepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Servicepage record, @Param("example") ServicepageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExample(@Param("record") Servicepage record, @Param("example") ServicepageExample example);
}