package com.xm.swc.dao;

import com.xm.swc.pojo.po.Tbconnection;
import com.xm.swc.pojo.po.TbconnectionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbconnectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbconnection
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int countByExample(TbconnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbconnection
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int deleteByExample(TbconnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbconnection
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insert(Tbconnection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbconnection
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int insertSelective(Tbconnection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbconnection
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    List<Tbconnection> selectByExample(TbconnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbconnection
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Tbconnection record, @Param("example") TbconnectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbconnection
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    int updateByExample(@Param("record") Tbconnection record, @Param("example") TbconnectionExample example);
}