package com.xm.swc.pojo.po;

public class Aboutpage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aboutpage.aboutId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String aboutid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aboutpage.aboutName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String aboutname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aboutpage.aboutContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String aboutcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aboutpage.aboutId
     *
     * @return the value of aboutpage.aboutId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getAboutid() {
        return aboutid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aboutpage.aboutId
     *
     * @param aboutid the value for aboutpage.aboutId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setAboutid(String aboutid) {
        this.aboutid = aboutid == null ? null : aboutid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aboutpage.aboutName
     *
     * @return the value of aboutpage.aboutName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getAboutname() {
        return aboutname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aboutpage.aboutName
     *
     * @param aboutname the value for aboutpage.aboutName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setAboutname(String aboutname) {
        this.aboutname = aboutname == null ? null : aboutname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aboutpage.aboutContent
     *
     * @return the value of aboutpage.aboutContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getAboutcontent() {
        return aboutcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aboutpage.aboutContent
     *
     * @param aboutcontent the value for aboutpage.aboutContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setAboutcontent(String aboutcontent) {
        this.aboutcontent = aboutcontent == null ? null : aboutcontent.trim();
    }
}