package com.xm.swc.pojo.po;

public class Portfoliopage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfoliopage.portfolioId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String portfolioid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfoliopage.portfolioName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String portfolioname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfoliopage.portfolioimgs
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String portfolioimgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfoliopage.portfolioOccupation
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String portfoliooccupation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfoliopage.portfolioId
     *
     * @return the value of portfoliopage.portfolioId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPortfolioid() {
        return portfolioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfoliopage.portfolioId
     *
     * @param portfolioid the value for portfoliopage.portfolioId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPortfolioid(String portfolioid) {
        this.portfolioid = portfolioid == null ? null : portfolioid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfoliopage.portfolioName
     *
     * @return the value of portfoliopage.portfolioName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPortfolioname() {
        return portfolioname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfoliopage.portfolioName
     *
     * @param portfolioname the value for portfoliopage.portfolioName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPortfolioname(String portfolioname) {
        this.portfolioname = portfolioname == null ? null : portfolioname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfoliopage.portfolioimgs
     *
     * @return the value of portfoliopage.portfolioimgs
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPortfolioimgs() {
        return portfolioimgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfoliopage.portfolioimgs
     *
     * @param portfolioimgs the value for portfoliopage.portfolioimgs
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPortfolioimgs(String portfolioimgs) {
        this.portfolioimgs = portfolioimgs == null ? null : portfolioimgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfoliopage.portfolioOccupation
     *
     * @return the value of portfoliopage.portfolioOccupation
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPortfoliooccupation() {
        return portfoliooccupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfoliopage.portfolioOccupation
     *
     * @param portfoliooccupation the value for portfoliopage.portfolioOccupation
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPortfoliooccupation(String portfoliooccupation) {
        this.portfoliooccupation = portfoliooccupation == null ? null : portfoliooccupation.trim();
    }
}