package com.xm.swc.pojo.po;

public class Pricingpage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pricingpage.pricingId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String pricingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pricingpage.pricingName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String pricingname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pricingpage.pricingContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String pricingcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pricingpage.pricingPrice
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String pricingprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pricingpage.pricingSelect
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String pricingselect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pricingpage.pricingId
     *
     * @return the value of pricingpage.pricingId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPricingid() {
        return pricingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pricingpage.pricingId
     *
     * @param pricingid the value for pricingpage.pricingId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPricingid(String pricingid) {
        this.pricingid = pricingid == null ? null : pricingid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pricingpage.pricingName
     *
     * @return the value of pricingpage.pricingName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPricingname() {
        return pricingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pricingpage.pricingName
     *
     * @param pricingname the value for pricingpage.pricingName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPricingname(String pricingname) {
        this.pricingname = pricingname == null ? null : pricingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pricingpage.pricingContent
     *
     * @return the value of pricingpage.pricingContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPricingcontent() {
        return pricingcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pricingpage.pricingContent
     *
     * @param pricingcontent the value for pricingpage.pricingContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPricingcontent(String pricingcontent) {
        this.pricingcontent = pricingcontent == null ? null : pricingcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pricingpage.pricingPrice
     *
     * @return the value of pricingpage.pricingPrice
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPricingprice() {
        return pricingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pricingpage.pricingPrice
     *
     * @param pricingprice the value for pricingpage.pricingPrice
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPricingprice(String pricingprice) {
        this.pricingprice = pricingprice == null ? null : pricingprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pricingpage.pricingSelect
     *
     * @return the value of pricingpage.pricingSelect
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getPricingselect() {
        return pricingselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pricingpage.pricingSelect
     *
     * @param pricingselect the value for pricingpage.pricingSelect
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setPricingselect(String pricingselect) {
        this.pricingselect = pricingselect == null ? null : pricingselect.trim();
    }
}