package com.xm.swc.pojo.po;

import java.util.ArrayList;
import java.util.List;

public class PricingpageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public PricingpageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPricingidIsNull() {
            addCriterion("pricingId is null");
            return (Criteria) this;
        }

        public Criteria andPricingidIsNotNull() {
            addCriterion("pricingId is not null");
            return (Criteria) this;
        }

        public Criteria andPricingidEqualTo(String value) {
            addCriterion("pricingId =", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidNotEqualTo(String value) {
            addCriterion("pricingId <>", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidGreaterThan(String value) {
            addCriterion("pricingId >", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidGreaterThanOrEqualTo(String value) {
            addCriterion("pricingId >=", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidLessThan(String value) {
            addCriterion("pricingId <", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidLessThanOrEqualTo(String value) {
            addCriterion("pricingId <=", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidLike(String value) {
            addCriterion("pricingId like", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidNotLike(String value) {
            addCriterion("pricingId not like", value, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidIn(List<String> values) {
            addCriterion("pricingId in", values, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidNotIn(List<String> values) {
            addCriterion("pricingId not in", values, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidBetween(String value1, String value2) {
            addCriterion("pricingId between", value1, value2, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingidNotBetween(String value1, String value2) {
            addCriterion("pricingId not between", value1, value2, "pricingid");
            return (Criteria) this;
        }

        public Criteria andPricingnameIsNull() {
            addCriterion("pricingName is null");
            return (Criteria) this;
        }

        public Criteria andPricingnameIsNotNull() {
            addCriterion("pricingName is not null");
            return (Criteria) this;
        }

        public Criteria andPricingnameEqualTo(String value) {
            addCriterion("pricingName =", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameNotEqualTo(String value) {
            addCriterion("pricingName <>", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameGreaterThan(String value) {
            addCriterion("pricingName >", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameGreaterThanOrEqualTo(String value) {
            addCriterion("pricingName >=", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameLessThan(String value) {
            addCriterion("pricingName <", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameLessThanOrEqualTo(String value) {
            addCriterion("pricingName <=", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameLike(String value) {
            addCriterion("pricingName like", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameNotLike(String value) {
            addCriterion("pricingName not like", value, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameIn(List<String> values) {
            addCriterion("pricingName in", values, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameNotIn(List<String> values) {
            addCriterion("pricingName not in", values, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameBetween(String value1, String value2) {
            addCriterion("pricingName between", value1, value2, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingnameNotBetween(String value1, String value2) {
            addCriterion("pricingName not between", value1, value2, "pricingname");
            return (Criteria) this;
        }

        public Criteria andPricingcontentIsNull() {
            addCriterion("pricingContent is null");
            return (Criteria) this;
        }

        public Criteria andPricingcontentIsNotNull() {
            addCriterion("pricingContent is not null");
            return (Criteria) this;
        }

        public Criteria andPricingcontentEqualTo(String value) {
            addCriterion("pricingContent =", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentNotEqualTo(String value) {
            addCriterion("pricingContent <>", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentGreaterThan(String value) {
            addCriterion("pricingContent >", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentGreaterThanOrEqualTo(String value) {
            addCriterion("pricingContent >=", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentLessThan(String value) {
            addCriterion("pricingContent <", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentLessThanOrEqualTo(String value) {
            addCriterion("pricingContent <=", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentLike(String value) {
            addCriterion("pricingContent like", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentNotLike(String value) {
            addCriterion("pricingContent not like", value, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentIn(List<String> values) {
            addCriterion("pricingContent in", values, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentNotIn(List<String> values) {
            addCriterion("pricingContent not in", values, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentBetween(String value1, String value2) {
            addCriterion("pricingContent between", value1, value2, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingcontentNotBetween(String value1, String value2) {
            addCriterion("pricingContent not between", value1, value2, "pricingcontent");
            return (Criteria) this;
        }

        public Criteria andPricingpriceIsNull() {
            addCriterion("pricingPrice is null");
            return (Criteria) this;
        }

        public Criteria andPricingpriceIsNotNull() {
            addCriterion("pricingPrice is not null");
            return (Criteria) this;
        }

        public Criteria andPricingpriceEqualTo(String value) {
            addCriterion("pricingPrice =", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceNotEqualTo(String value) {
            addCriterion("pricingPrice <>", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceGreaterThan(String value) {
            addCriterion("pricingPrice >", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceGreaterThanOrEqualTo(String value) {
            addCriterion("pricingPrice >=", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceLessThan(String value) {
            addCriterion("pricingPrice <", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceLessThanOrEqualTo(String value) {
            addCriterion("pricingPrice <=", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceLike(String value) {
            addCriterion("pricingPrice like", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceNotLike(String value) {
            addCriterion("pricingPrice not like", value, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceIn(List<String> values) {
            addCriterion("pricingPrice in", values, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceNotIn(List<String> values) {
            addCriterion("pricingPrice not in", values, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceBetween(String value1, String value2) {
            addCriterion("pricingPrice between", value1, value2, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingpriceNotBetween(String value1, String value2) {
            addCriterion("pricingPrice not between", value1, value2, "pricingprice");
            return (Criteria) this;
        }

        public Criteria andPricingselectIsNull() {
            addCriterion("pricingSelect is null");
            return (Criteria) this;
        }

        public Criteria andPricingselectIsNotNull() {
            addCriterion("pricingSelect is not null");
            return (Criteria) this;
        }

        public Criteria andPricingselectEqualTo(String value) {
            addCriterion("pricingSelect =", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectNotEqualTo(String value) {
            addCriterion("pricingSelect <>", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectGreaterThan(String value) {
            addCriterion("pricingSelect >", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectGreaterThanOrEqualTo(String value) {
            addCriterion("pricingSelect >=", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectLessThan(String value) {
            addCriterion("pricingSelect <", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectLessThanOrEqualTo(String value) {
            addCriterion("pricingSelect <=", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectLike(String value) {
            addCriterion("pricingSelect like", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectNotLike(String value) {
            addCriterion("pricingSelect not like", value, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectIn(List<String> values) {
            addCriterion("pricingSelect in", values, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectNotIn(List<String> values) {
            addCriterion("pricingSelect not in", values, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectBetween(String value1, String value2) {
            addCriterion("pricingSelect between", value1, value2, "pricingselect");
            return (Criteria) this;
        }

        public Criteria andPricingselectNotBetween(String value1, String value2) {
            addCriterion("pricingSelect not between", value1, value2, "pricingselect");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pricingpage
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 08 12:35:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pricingpage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}