package com.xm.swc.pojo.po;

public class Servicepage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicepage.serviceId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicepage.serviceName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String servicename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicepage.serviceContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String servicecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicepage.serviceIcon
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String serviceicon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicepage.serviceId
     *
     * @return the value of servicepage.serviceId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicepage.serviceId
     *
     * @param serviceid the value for servicepage.serviceId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid == null ? null : serviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicepage.serviceName
     *
     * @return the value of servicepage.serviceName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getServicename() {
        return servicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicepage.serviceName
     *
     * @param servicename the value for servicepage.serviceName
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setServicename(String servicename) {
        this.servicename = servicename == null ? null : servicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicepage.serviceContent
     *
     * @return the value of servicepage.serviceContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getServicecontent() {
        return servicecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicepage.serviceContent
     *
     * @param servicecontent the value for servicepage.serviceContent
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setServicecontent(String servicecontent) {
        this.servicecontent = servicecontent == null ? null : servicecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicepage.serviceIcon
     *
     * @return the value of servicepage.serviceIcon
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getServiceicon() {
        return serviceicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicepage.serviceIcon
     *
     * @param serviceicon the value for servicepage.serviceIcon
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setServiceicon(String serviceicon) {
        this.serviceicon = serviceicon == null ? null : serviceicon.trim();
    }
}