package com.xm.swc.pojo.po;

import java.util.ArrayList;
import java.util.List;

public class ServicepageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public ServicepageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andServiceidIsNull() {
            addCriterion("serviceId is null");
            return (Criteria) this;
        }

        public Criteria andServiceidIsNotNull() {
            addCriterion("serviceId is not null");
            return (Criteria) this;
        }

        public Criteria andServiceidEqualTo(String value) {
            addCriterion("serviceId =", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotEqualTo(String value) {
            addCriterion("serviceId <>", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThan(String value) {
            addCriterion("serviceId >", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThanOrEqualTo(String value) {
            addCriterion("serviceId >=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThan(String value) {
            addCriterion("serviceId <", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThanOrEqualTo(String value) {
            addCriterion("serviceId <=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLike(String value) {
            addCriterion("serviceId like", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotLike(String value) {
            addCriterion("serviceId not like", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidIn(List<String> values) {
            addCriterion("serviceId in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotIn(List<String> values) {
            addCriterion("serviceId not in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidBetween(String value1, String value2) {
            addCriterion("serviceId between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotBetween(String value1, String value2) {
            addCriterion("serviceId not between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServicenameIsNull() {
            addCriterion("serviceName is null");
            return (Criteria) this;
        }

        public Criteria andServicenameIsNotNull() {
            addCriterion("serviceName is not null");
            return (Criteria) this;
        }

        public Criteria andServicenameEqualTo(String value) {
            addCriterion("serviceName =", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameNotEqualTo(String value) {
            addCriterion("serviceName <>", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameGreaterThan(String value) {
            addCriterion("serviceName >", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameGreaterThanOrEqualTo(String value) {
            addCriterion("serviceName >=", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameLessThan(String value) {
            addCriterion("serviceName <", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameLessThanOrEqualTo(String value) {
            addCriterion("serviceName <=", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameLike(String value) {
            addCriterion("serviceName like", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameNotLike(String value) {
            addCriterion("serviceName not like", value, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameIn(List<String> values) {
            addCriterion("serviceName in", values, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameNotIn(List<String> values) {
            addCriterion("serviceName not in", values, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameBetween(String value1, String value2) {
            addCriterion("serviceName between", value1, value2, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicenameNotBetween(String value1, String value2) {
            addCriterion("serviceName not between", value1, value2, "servicename");
            return (Criteria) this;
        }

        public Criteria andServicecontentIsNull() {
            addCriterion("serviceContent is null");
            return (Criteria) this;
        }

        public Criteria andServicecontentIsNotNull() {
            addCriterion("serviceContent is not null");
            return (Criteria) this;
        }

        public Criteria andServicecontentEqualTo(String value) {
            addCriterion("serviceContent =", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentNotEqualTo(String value) {
            addCriterion("serviceContent <>", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentGreaterThan(String value) {
            addCriterion("serviceContent >", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentGreaterThanOrEqualTo(String value) {
            addCriterion("serviceContent >=", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentLessThan(String value) {
            addCriterion("serviceContent <", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentLessThanOrEqualTo(String value) {
            addCriterion("serviceContent <=", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentLike(String value) {
            addCriterion("serviceContent like", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentNotLike(String value) {
            addCriterion("serviceContent not like", value, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentIn(List<String> values) {
            addCriterion("serviceContent in", values, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentNotIn(List<String> values) {
            addCriterion("serviceContent not in", values, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentBetween(String value1, String value2) {
            addCriterion("serviceContent between", value1, value2, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServicecontentNotBetween(String value1, String value2) {
            addCriterion("serviceContent not between", value1, value2, "servicecontent");
            return (Criteria) this;
        }

        public Criteria andServiceiconIsNull() {
            addCriterion("serviceIcon is null");
            return (Criteria) this;
        }

        public Criteria andServiceiconIsNotNull() {
            addCriterion("serviceIcon is not null");
            return (Criteria) this;
        }

        public Criteria andServiceiconEqualTo(String value) {
            addCriterion("serviceIcon =", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconNotEqualTo(String value) {
            addCriterion("serviceIcon <>", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconGreaterThan(String value) {
            addCriterion("serviceIcon >", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconGreaterThanOrEqualTo(String value) {
            addCriterion("serviceIcon >=", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconLessThan(String value) {
            addCriterion("serviceIcon <", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconLessThanOrEqualTo(String value) {
            addCriterion("serviceIcon <=", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconLike(String value) {
            addCriterion("serviceIcon like", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconNotLike(String value) {
            addCriterion("serviceIcon not like", value, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconIn(List<String> values) {
            addCriterion("serviceIcon in", values, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconNotIn(List<String> values) {
            addCriterion("serviceIcon not in", values, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconBetween(String value1, String value2) {
            addCriterion("serviceIcon between", value1, value2, "serviceicon");
            return (Criteria) this;
        }

        public Criteria andServiceiconNotBetween(String value1, String value2) {
            addCriterion("serviceIcon not between", value1, value2, "serviceicon");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicepage
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 08 12:35:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table servicepage
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}