package com.xm.swc.pojo.po;

public class Tbconnection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbconnection.qqNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String qqnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbconnection.wechatNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String wechatnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbconnection.weiBoNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String weibonumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbconnection.mailNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String mailnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbconnection.telephone
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbconnection.connectId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String connectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbconnection.qqNumber
     *
     * @return the value of tbconnection.qqNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getQqnumber() {
        return qqnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbconnection.qqNumber
     *
     * @param qqnumber the value for tbconnection.qqNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setQqnumber(String qqnumber) {
        this.qqnumber = qqnumber == null ? null : qqnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbconnection.wechatNumber
     *
     * @return the value of tbconnection.wechatNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getWechatnumber() {
        return wechatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbconnection.wechatNumber
     *
     * @param wechatnumber the value for tbconnection.wechatNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setWechatnumber(String wechatnumber) {
        this.wechatnumber = wechatnumber == null ? null : wechatnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbconnection.weiBoNumber
     *
     * @return the value of tbconnection.weiBoNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getWeibonumber() {
        return weibonumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbconnection.weiBoNumber
     *
     * @param weibonumber the value for tbconnection.weiBoNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setWeibonumber(String weibonumber) {
        this.weibonumber = weibonumber == null ? null : weibonumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbconnection.mailNumber
     *
     * @return the value of tbconnection.mailNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getMailnumber() {
        return mailnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbconnection.mailNumber
     *
     * @param mailnumber the value for tbconnection.mailNumber
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setMailnumber(String mailnumber) {
        this.mailnumber = mailnumber == null ? null : mailnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbconnection.telephone
     *
     * @return the value of tbconnection.telephone
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbconnection.telephone
     *
     * @param telephone the value for tbconnection.telephone
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbconnection.connectId
     *
     * @return the value of tbconnection.connectId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getConnectid() {
        return connectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbconnection.connectId
     *
     * @param connectid the value for tbconnection.connectId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setConnectid(String connectid) {
        this.connectid = connectid == null ? null : connectid.trim();
    }
}