package com.xm.swc.pojo.po;

public class Tbimage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbimage.imgId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String imgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbimage.imgUrl
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbimage.imgUid
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String imguid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbimage.imgId
     *
     * @return the value of tbimage.imgId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbimage.imgId
     *
     * @param imgid the value for tbimage.imgId
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setImgid(String imgid) {
        this.imgid = imgid == null ? null : imgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbimage.imgUrl
     *
     * @return the value of tbimage.imgUrl
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbimage.imgUrl
     *
     * @param imgurl the value for tbimage.imgUrl
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbimage.imgUid
     *
     * @return the value of tbimage.imgUid
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getImguid() {
        return imguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbimage.imgUid
     *
     * @param imguid the value for tbimage.imgUid
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setImguid(String imguid) {
        this.imguid = imguid == null ? null : imguid.trim();
    }
}