package com.xm.swc.pojo.po;

public class Userdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdata.uname
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdata.upassword
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String upassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdata.uid
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdata.uname
     *
     * @return the value of userdata.uname
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdata.uname
     *
     * @param uname the value for userdata.uname
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdata.upassword
     *
     * @return the value of userdata.upassword
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdata.upassword
     *
     * @param upassword the value for userdata.upassword
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword == null ? null : upassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdata.uid
     *
     * @return the value of userdata.uid
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdata.uid
     *
     * @param uid the value for userdata.uid
     *
     * @mbggenerated Mon Oct 08 12:35:29 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}